### ISSUE TITLE
Video path

### ISSUE THREAD

**Issue by philipgriffin** [DevExpress/testcafe-reporter-json#7] opened 2019-07-27 13:18 UTC
Hi,

I am currently running testcafe with screenshots and getting the screenshot path as part of the fixture payload. However, when running with video for failed test runs I do not get the path to the video. 

Is this possible to get?

**Comment by miherlosev** [comment] 2019-07-29 09:50
Duplicate of https://github.com/DevExpress/testcafe/issues/4080

**Closed as completed by miherlosev** 2019-07-29 09:50 UTC
Labels: duplicate
